import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Notification from './components/common/notificatios/Notification';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Image Slideshow Maker',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Notification />
      </body>
    </html>
  );
}
